// app/projects/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Header from "../components/Header";
import Footer from "../components/Footer";

import '../../styles/about-us.css';


export default function AboutUsPage() {
    return (
        <div>
            <Header />
            <div className="sections overflow-hidden">
                <div className="hero-sec position-static">
                    <div className="container">
                        <h1 className="main-title text-center mb-4">Privacy Policy</h1>
                        <div className="content-wrapper" style={{maxWidth: '100%'}}>
                            <div className="fs-4 fw-semibold mb-2">What we Agree</div>
                            <p className="mb-3 fw-medium">
                                1.  In respect to Registered user of our website, all leads are generated by other registered users of our
                                website and no consumer leads are generated on our site{' '}
                                <Link href="#" className="text-decoration-none fw-bold text-dark">
                                    EZ subcontractor.com
                                </Link>{' '}
                                is only a web portal by which General contractors can communicate to specialty contractors by posting bids
                                for their projects and EZ subcontractor.com cannot guarantee the accuracy of the posts.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
}